---
servers:
  hosts:
    docker-standalone:
      ansible_host: 192.168.1.196 # l'ip de votre serveur ubuntu 24.04
      ansible_user: iliade # Remplacez par votre utilisateur sudo
      ansible_ssh_private_key_file: ~/.ssh/id_rsa # chemin de votre cl√© sur la machine local
